apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gotway
  namespace: gotway
spec:
  dependsOn:
    - name: redis
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-tenant-gotway
    namespace: flux-system
  path: ./apps/gotway
  prune: true
  timeout: 5m
