apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
spec:
  releaseName: redis
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: mmontes
        namespace: flux-system
      version: "0.3.0"
  interval: 5m
  values:
    image:
      repository: redis
      pullPolicy: IfNotPresent
      tag: 6.2.6-alpine3.15

    storage:
      size: 300Mi
      className: local-path
      accessModes:
        - "ReadWriteOnce"

    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        cpu: 300m
        memory: 500Mi

    nodeSelector:
      node.mmontes.io/type: compute
