apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gotway
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: gotway
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
