apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gotway
  namespace: gotway
spec:
  encryptedData:
    REDIS_URL: AgBUcCKtE3UYrBmdocF8dZZde0OA8acgtNrELbM3ky0pCZmueEE2ekMKfo2ZI+7bYMF33F6DPmoYcADmMR2lBQcOHXCuOsZPW83NUy1Mn6g7dJfc6NKzGgdaJ+YiDuMJnkBMnulU9NqqREVlr2hvn90jc1B75vGpQVKCNlvcqwjSUs7ZxTs7N+7iPHRHg2vUY3+hyrjaFE+Vo93OO3NUCfH7tFYpCDHP7NkerVQ7QJePv1cjxUb8h6PEzORHNMt3QvCNeGL3hhcTWjm0CggchxuOs0RFTM9yhMZqtWZ+fX5L0TXAb0IxOt0lVrhhscmxXyG+IxafXg0FgCN8zOxkBpPBAkrq7aeM72VIv+bl8hItc7EUn2IU/0nnjdV3rTcyxR3ixKX6OzgHtkzuOjcm05MRlzoAM6+CcG0npa4a1jVHZOUbY65KFnxkbvLsJeHbDNVulz4eChX0a9qka1VM1nP/sHLPS6wTtM82mvKaH6ijgh1ZD1DXd/zXS3LoQhBxmXfvuQb3w6ptpXev0VYbv6Z1sggD8Kuu9c5VKbc8ZPwQ7O73dAGuSOqUOHY2rXbfHyprzKPEJd5+Ezs1URJSICgmstz2ueXKfNbOwBqJ+7ZzJDHX2/cWUfKjKRtRqKsRDMAWKlqhw5vQt+vQV1H+M8PvSr/ugXElz6rKzfc9bDnARYF3WB3lA0FRwZLbnIJMFquR/UjdpdW1QVaW+MDCDyz2AIMJJBI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gotway
      namespace: gotway

